name: 4 Latest blog post workflow
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with the latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "5"
          retry_count: 3
          retry_wait_time: 5
          feed_list: "https://dev.to/feed/apoorvtyagi"
