name: Update Quote Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * *" # Runs at 12:30 AM UTC everyday

jobs:
  update-readme:
    name: Update Quote README
    runs-on: ubuntu-latest
    steps:
      - uses: ApoorvTyagi/quote-readme@main
        with:
          OPTION: both 
